### ISSUE TITLE
zu den Übersetzungshinweisen

### ISSUE THREAD

**Issue by joliss** [molily/jscore-de#11]
Hi Mathias, ich habe grad einen Blick auf Übersetzungshinweise am Anfang der [index.html](https://github.com/molily/jscore-de/blob/master/2/index.html) geworfen. Ich hätte folgende Vorschläge:

> evaluate, evaluation
> meistens: Ausführung, nicht Berechnung

"Ausführung" klingt für mich nach *execution*. Wie wäre es mit "Auswertung"?

> dispatch
> Auslieferung
>   oder Bindung
>   oder Zustellung
>   oder Versenden, Absenden
>   oder Abarbeitung

"Dispatch" kommt hier glaube ich nur im Zusammenhang von "static/dynamic dispatch" vor. Ich tue mich mit der Übersetzung etwas schwer, aber Google meint, dass ["dynamische Bindung"](https://www.google.de/search?q=%22dynamische+bindung%22&hl=de) anscheinend der gängigste Ausdruck ist.

**Comment by molily** [comment]
Danke erst einmal!

»Ausführung« ist nicht die korrekte Übersetzung für »evaluation«, das stimmt. »Berechnung« passte sehr schlecht an den Stellen, wo es benutzt wird. »Auswertung« werde ich einmal prüfen, danke.

Unter dem Begriff der »Dynamischen Bindung« kenne ich das Konzept auch. Ich hatte »Auslieferung« benutzt, weil es mir [im ursprünglichen OOP-Modell nach Alan Kay](https://de.wikipedia.org/wiki/Objektorientierte_Programmierung#Definition) passend erschien. Es wird eine »Nachricht« an das Objekt gesendet und eben dynamisch »zugestellt« (das meint »dispatch«, soweit ich es verstehe). Diesen Aspekt von »dispatch« drückt »Bindung« leider nicht aus. Letztlich werde ich wohl den gängigen Begriff benutzen, falls mir kein besserer unterkommt.
