### ISSUE TITLE
Übersetzung von Object.prototype als Objekt.prototype

### ISSUE THREAD

**Issue by martin-honnen** [molily/jscore-de#14]
In dem Hinweis `Standardmäßig erben Objekte von <code>Objekt.prototype</code>` in https://github.com/molily/jscore-de/blob/master/2/index.html scheint mir der Versuch, im Javascript-Code `Object.prototype` zu übersetzen und als `Objekt.prototype` einzudeutschen, eher zweifelhaft. An anderen Stellen im Artikel wird das auch nicht gemacht, z.b. in `Standard-Prototypen Object.prototype` wird die englische Schreibweise benutzt.

**Comment by molily** [comment]
Danke. Das war ein Versehen. :)
